stoarca/xdotoolify.js

src/xdotoolify.js
Often we have failures such as:
`element is null` and no stack trace
With this change, you should expect:
`Element for selector "<selector>" not found'` and the stack trace
=> Check for null element and raise selector exception

README.md
When selector is an array, the second element of the selector argument corresponds to the index in the zero-based Nodelist that querySelectorAll returns. The example should read 'third' and not 'second' for integer 2.
=> Fixed misleading text in README

package-lock.json, package.json, src/xdotoolify.js, test/xdotoolify-spec.js
Added a check after every interaction (click, button press, etc.) for a checkUntil. This check can be skipped by running in a few ways:
- running the interaction with checkAfter == false,
- running do() with option.unsafe == true
- running checkNothing right after interaction
If these conditions are not met, and an interaction is not followed by a checkUntil, an error is thrown.
=> Added checkUntil requirement after interaction

package-lock.json, package.json, src/xdotoolify.js, test/xdotoolify-spec.js
There was a bug in which only the first .do() statement to run would set the unsafe property. Because of this, subsequent unsafe do() calls would fail even on the same recursion level. Added code so that the value for unsafe is set at the highest recursion level for every do() function. A second bug is also fixed, in which it was previously allowed to have chains such as `unsafe > safe > unsafe`. Now, `unsafe` statements are not allowed anywhere under a `safe` ones, even if the outermost statement is an `unsafe` one.
=> Bug fix: nested and sibling statements

src/xdotoolify.js, test/xdotoolify-spec.js
Deprecating 'check' actions so that they throw an error when run within a safe `do` statement. Added tests and modified old related ones.
=> Deprecated "check" actions

package-lock.json, package.json, src/xdotoolify.js
I made changes to allow for mousemove to be run with the same position, and made it the default option for `auto` functions (e.g. `autoClick`, `autoKey`).
=> Allow same mouse position in auto functions

package-lock.json, package.json, src/xdotoolify.js
I added an argument to Xdotoolify to accept an initial object to store the last mouse position. This allows multiple pages to share the same global mouse position.
=> Adding option to use global xjsLastPosition for different pages

package-lock.json, package.json, src/xdotoolify.js
1) Added a check until every click of types 1, 2, and 3 to ensure that a) the click event is registered before continuing and b) the clicked element is either a descendant of or the exact element given by the selector.
2) Added a check inside `_getElementAndBrowserRect` to ensure the element given by the selector is not in a different frame or a frame itself.
=> Added check after clicks to ensure they click the correct element

package-lock.json, package.json, src/xdotoolify.js
There was a previous issue where using coordinate selectors or relative position ones would lead to an error during verification, as it would try to find an element using the selector. Fixed this issue.
=> Ignore coordinate seletors during click verification

package-lock.json, package.json, src/xdotoolify.js
Promise would go past resolve statements and fail sometimes. Fixed by returning right after resolve.
=> Returning after waitForClickAction promise resolved

package-lock.json, package.json, src/xdotoolify.js
Cleaning up command array before adding click listener. This is done to avoid removing the listener on the wrong kind of events.
=> Clearing command array before adding click listener

package-lock.json, package.json, src/xdotoolify.js, test/xdotoolify-spec.js
I added a `addRequireCheckImmediatelyAfter` function which can be added to custom functions to enforce checking after they are run. I also noticed some bugs. For example old line 974 had `if (op.mouseButton in [1, 2, 3] ...)`. I was thinking of `in` as in Python, where it checks that the given object is an element of the array, but it actually takes `op.mouseButton` as an index and checks if it exists in the array. For almost every case, this would have worked (since 1 is an index in the array), but this could have led to future problems.
=> addRequireCheckImmediatelyAfter

package-lock.json, package.json
It seems the `prepublish` script in `package.json` is deprecated ([see here](https://docs.npmjs.com/cli/v8/using-npm/scripts)). I replaced it with `prepare`.
=> Replaced "prepublish" with "prepare"

package-lock.json, package.json, src/xdotoolify.js, test/xdotoolify-spec.js
Added `Xdotoolify.arg`, which wraps a function which can then be used as an argument for other Xdotoolify functions. Also added `_Xdoolify.saveValue` and `Xdotoolify.getSavedValue`, which can be used to save variables for later use. Also added tests for this, and expanded coverage for `addRequireCheckImmediatelyAfter`.
=> Accept function as argument + save values for later use

package-lock.json, package.json, src/xdotoolify.js
There was an bug in which `_waitForClickAction` would fail to return an error message in the case in which a click was not registered. It would instead return `window.clickInfo.error`, whose default value is `null`, which would be counted as a passing case.
=> Fixed click verification bug

package-lock.json, package.json, src/xdotoolify.js
Missed the `reject` argument in the previous version.
=> Added missing "reject" argument

package-lock.json, package.json, src/xdotoolify.js
The click event listener sometimes fails to register clicks when switching from one textarea to another one. This is not normally accompanied by a failure, so a warning is raised instead of throwing an error.
=> Raise warning instead of failure when click check fails

package-lock.json, package.json, src/xdotoolify.js
On the last update I made changes so that 'timed out' clicks that would raise a warning instead of throwing an error. However, the catch block also caught clicks that _were_ registered on the wrong element, leading to the wrong message being printed. This PR fixes this issue.
=> Fixed bug where misclicks were caught and wrong warning was printed

package-lock.json, package.json, src/xdotoolify.js
There was an issue when getting the visible bounding rect for fixed elements. The function kept looping through the parents to find one with `auto`, `scroll`, or `hidden` values in its overflow style, continuously checking that the element was not hidden due to this. This breaks with `fixed` elements, though, since they exist outside the normal flow. The function was changed so that it breaks when it encounters a `fixed` element, instead of continuing to inspect its parents.
=> Fixed "getElementVisibleBoundingRect" for fixed elements

package-lock.json, package.json, src/xdotoolify.js
most calls to `_do` had undefined values for page, which made the DOM wait skip instead of doing what it's supposed to. Fixed.
=> Fixed but were DOM wait would not run

package-lock.json, package.json, src/xdotoolify.js
There was an error caused by the last update when tabs were closed. Catching that error and ignoring it.
=> Catching "NoSuchWindowError" when tabs are closed
